import logging
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

from simple_parsing import ArgumentParser, DashVariant

from varpubs.cache import Cache
from varpubs.pubmed_db import PubmedDB
from varpubs.summarize import PubmedSummarizer, Settings

logger = logging.getLogger(__name__)


@dataclass
class DeployDBArgs:
    """
    Command-line arguments for deploying the PubMed variant database.

    - db_path: Path to the DuckDB database file to be created or updated.
    - vcf_paths: List of VCF files containing variant information.
    - species: Species for variant annotation (default: human).
    - max_publications: Maximum number of publications to retrieve per variant (default: 50).
    """

    db_path: Path
    vcf_paths: List[Path]
    species: str = "human"
    max_publications: int = 50


@dataclass
class SummarizeArgs:
    """
    Command-line arguments for summarizing PubMed articles related to variants.

    - db_path: Path to the existing DuckDB database file.
    - vcf_path: A single annotated VCF file with variant terms.
    - output: Path to save the final variant summary file (bcf).
    - cache: Path to cache file to look up summary results instead of LLM usage
    - api_key: Hugging Face API token for model access.
    - judges: List of judges for ranking articles (e.g., "therapy relevance")
    - llm_url: Base URL for LLM API (Must follow the openai API format)
    - species: Species for variant annotation (default: human).
    - model: The LLM model used for summarization (default: medgemma-27b-it).
    - role: The professional role or perspective the LLM should take (default: physician).
    - output_cache: Optional path to save the cache file for storing new summary results.
    """

    db_path: Path
    vcf_path: Path
    output: Path
    cache: Optional[Path]
    llm_url: str
    species: str = "human"
    model: str = "medgemma-27b-it"
    role: str = "physician"
    judges: Optional[List[str]] = None
    api_key: Optional[str] = ""
    output_cache: Optional[Path] = None


@dataclass
class UpdateCacheArgs:
    """
    Arguments for updating the cache.

    - cache: List of paths to cache files generated by the 'summarize-variants' command.
    - output: Path to the cache file for storing new summary results. Will be created if it doesn't exist.
    - overwrite: Whether to overwrite existing cache entries.
    """

    cache: List[Path]
    output: Path
    overwrite: bool = False


def main():
    """
    Entry point for the varpubs CLI tool.

    Supports two commands:
    - 'deploy-db': Parses VCFs and populates the DuckDB database with PubMed entries.
    - 'summarize-variants': Summarizes articles related to variants using an LLM model.
    """
    parser = ArgumentParser(add_option_string_dash_variants=DashVariant.DASH)
    subparsers = parser.add_subparsers(dest="command", required=True)

    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help="Increase verbosity level (use -v, -vv, -vvv)",
    )

    deploy_parser = subparsers.add_parser("deploy-db", help="Deploy the database")
    deploy_parser.add_arguments(DeployDBArgs, dest="args")

    summarize_parser = subparsers.add_parser(
        "summarize-variants", help="Summarize variants using LLM"
    )
    summarize_parser.add_arguments(SummarizeArgs, dest="args")

    update_cache_parser = subparsers.add_parser(
        "update-cache",
        help="Update cache using temporary caches from summarize-variants subcommand",
    )
    update_cache_parser.add_arguments(UpdateCacheArgs, dest="args")

    args = parser.parse_args()

    level = logging.WARNING
    if args.verbose == 1:
        level = logging.INFO
    elif args.verbose >= 2:
        level = logging.DEBUG
    logging.basicConfig(level=level)

    if args.command == "deploy-db":
        db = PubmedDB(
            path=args.args.db_path,
            vcf_paths=args.args.vcf_paths,
            species=args.args.species,
            max_publications=args.args.max_publications,
        )
        db.deploy()

    elif args.command == "summarize-variants":
        from varpubs.summarize_variants import summarize_variants

        cache = Cache(args.args.cache) if args.args.cache else None

        summarizer = PubmedSummarizer(
            settings=Settings(
                api_key=args.args.api_key,
                model=args.args.model,
                base_url=args.args.llm_url,
                role=args.args.role,
                cache=cache,
            )
        )

        summarize_variants(
            db_path=args.args.db_path,
            vcf_path=args.args.vcf_path,
            summarizer=summarizer,
            judges=args.args.judges,
            species=args.args.species,
            out_path=args.args.output,
            output_cache=args.args.output_cache,
        )

    elif args.command == "update-cache":
        cache = Cache(args.args.output)
        cache.deploy()
        for c in args.args.cache:
            other_cache = Cache(c)
            cache.merge(other_cache, overwrite=args.args.overwrite)
            logger.info(f"Succesfully merged cache {c} into {args.args.output}")
